#!/usr/bin/env python3
"""cook_plan.py — DETERMINISTIC cook-plan generator. No AI.

Generates the phone-readable `cycles/<date>-cook-plan.md` artifact for a cycle —
the file Will actually reads on his phone at Costco and at the stove. The
2026-07-18 plan was hand-written and valued; this makes one every cycle.

What it fills in deterministically (from the other scripts, run in-process as
subprocesses with --json):
  - Buy list split by store (grocery.py BUY items; CHECK items as a confirm list)
  - Saturday cooks / Sunday preps split from cook_schedule.py's priority order,
    per the WEEKEND-COOK model (config.weekend_cook): all cooking Sat+Sun,
    aging/perishable cook is Sat cook #1, rotisserie is a Saturday anchor,
    Sat M2 = hot dogs (no cook), 3-4 cooks Sat + 3-4 preps Sun
  - Defrost / pack-swap checklist (defrost.py move lines + the fresh-vs-frozen
    pack-swap and day-old-rice rules from config)
  - Week-at-a-glance table SKELETON from the cycle's slot_assignments (the
    schema has no per-day mapping, so day cells are TODO — fill by hand/agent)
  - Will's daily macro line template from config.cut (protein target + the
    macro-closer preference)

It's a SCAFFOLD: generate, then hand-edit portions/day-mapping. Refuses to
overwrite an existing cook-plan unless --force (your edits are the artifact).

Usage:
  python cook_plan.py [cycles/<date>.yaml] [--force]
  make cook-plan [CYCLE=cycles/<date>.yaml]
"""
import json
import os
import subprocess
import sys
from datetime import date, timedelta
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from lib import models

SCRIPTS = Path(__file__).resolve().parent
DAYS = ["Sat", "Sun", "Mon", "Tue", "Wed", "Thu", "Fri"]


def run_json(script, cycle_path):
    env = {**os.environ, "PYTHONIOENCODING": "utf-8"}
    r = subprocess.run([sys.executable, str(SCRIPTS / script), str(cycle_path), "--json"],
                       capture_output=True, text=True, encoding="utf-8", errors="replace", env=env)
    try:
        return json.loads(r.stdout)
    except (ValueError, TypeError):
        return {}


def parse_iso(s, default=None):
    try:
        y, m, d = str(s).split("-")
        return date(int(y), int(m), int(d))
    except Exception:
        return default


def main():
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except (AttributeError, ValueError):
        pass
    force = "--force" in sys.argv
    args = [a for a in sys.argv[1:] if not a.startswith("-")]
    cycle_path = Path(args[0]) if args else models.latest_cycle_path()
    if not cycle_path or not Path(cycle_path).exists():
        print("No cycle file. Run `make new-cycle` or pass cycles/<date>.yaml."); sys.exit(1)

    cycle = models.load_cycle(cycle_path)
    config = models.load_config()
    recipes = {r.id: r for r in models.load_recipes()}
    out_path = Path(cycle_path).parent / f"{Path(cycle_path).stem}-cook-plan.md"
    if out_path.exists() and not force:
        print(f"{out_path.name} already exists — it may carry hand edits. Use --force to regenerate.")
        sys.exit(1)

    start = parse_iso(cycle.date, date.today())
    end = start + timedelta(days=6)
    grocery = run_json("grocery.py", cycle_path)
    schedule = run_json("cook_schedule.py", cycle_path)
    defrost = run_json("defrost.py", cycle_path)

    wc = config.get("weekend_cook", {}) or {}
    cut = config.get("cut", {}) or {}
    closer = (cut.get("macro_closer", {}) or {})

    L = []
    L.append(f"# Cook Plan — Cycle Sat {start.month}/{start.day} → Fri {end.month}/{end.day}")
    L.append("")
    L.append(f"**Weekend-cook model:** {wc.get('model', 'all cooking Sat+Sun; the week eats leftovers/reheats')}. "
             f"Sat M2 = hot dogs (no cook). *(generated by `make cook-plan` — edit freely, this file is the phone artifact)*")
    L.append("")
    L.append("---")
    L.append("")

    # ---- Buy list ----
    L.append("## 🛒 Buy list  (Walmart order Fri night · Costco Sat AM)")
    L.append("")
    stores = (grocery.get("stores") or {})
    for store in ["Costco", "Walmart", "Asian Mart"]:
        buys = [i for i in stores.get(store, []) if i.get("status") == "BUY"]
        if buys:
            L.append(f"**{store}:** " + " · ".join(i["item"] for i in buys))
            L.append("")
    checks = [i for s in stores.values() for i in s if i.get("status") == "CHECK"]
    if checks:
        L.append("**Confirm on hand (never assume):** " + " · ".join(dict.fromkeys(i["item"] for i in checks)))
        L.append("")
    L.append("---")
    L.append("")

    # ---- Sat/Sun split from the priority-ordered schedule ----
    cooks = schedule.get("cooks", [])
    n = len(cooks)
    sat_n = min(4, max(3, (n + 1) // 2)) if n > 1 else n   # 3-4 cooks Sat, rest Sun
    sat, sun = cooks[:sat_n], cooks[sat_n:]

    L.append(f"## 🍳 SATURDAY — {len(sat)} cook(s)  *(aging-ingredient dish goes FIRST)*")
    L.append("")
    for i, c in enumerate(sat, 1):
        L.append(f"**{i}. [#{c['recipe_id']}] {c['recipe']}** — {c['servings']} srv  *( {c['why']} )*")
        for rule in c.get("rules", []):
            L.append(f"   - rule: {rule}")
    L.append("")
    L.append("**Sat preps (15 min):**")
    L.append("- [ ] PACK SWAP check: if a cook moved earlier, it uses a FRESH same-day-bought "
             "protein pack; move frozen packs freezer→fridge for the later cook")
    L.append("- [ ] Day-old rice: any fried-rice recipe → cook its rice TODAY, fry tomorrow")
    L.append("- [ ] Pull tomorrow's frozen protein tonight (see defrost below)")
    L.append("")
    L.append(f"## 🍳 SUNDAY — {len(sun)} prep(s)")
    L.append("")
    for i, c in enumerate(sun, 1):
        L.append(f"**{i}. [#{c['recipe_id']}] {c['recipe']}** — {c['servings']} srv  *( {c['why']} )*")
        for rule in c.get("rules", []):
            L.append(f"   - rule: {rule}")
    L.append("- [ ] + cube in-season fruit for the week's M3 fruit cups")
    L.append("")

    # ---- Defrost ----
    moves = defrost.get("stage_from_freezer", [])
    if moves:
        L.append("**Defrost moves:**")
        for m in moves:
            L.append(f"- [ ] {m['move_date']}: {m['protein']} for {m['recipe']} "
                     f"(thaws {m['thaw_lo_h']}–{m['thaw_hi_h']}h)")
        L.append("")
    L.append("---")
    L.append("")

    # ---- Week at a glance (skeleton — day mapping is not in the schema) ----
    L.append("## 📅 Week at a glance  *(TODO: fill day cells — schema has no per-day mapping)*")
    L.append("")
    L.append("| Day | Will M4 | Elena M4 | Elena M2 |")
    L.append("|---|---|---|---|")
    for d in DAYS:
        L.append(f"| {d} | TODO | TODO | TODO |")
    L.append("")
    L.append("Servings to place (from the cycle's slot_assignments):")
    for sel in cycle.selections:
        rid = str(sel.get("recipe_id", ""))
        rname = recipes[rid].name if rid in recipes else "?"
        for sa in sel.get("slot_assignments", []):
            L.append(f"- #{rid} {rname}: {sa.get('servings')}x {sa.get('member')} {sa.get('slot')}")
    L.append("")

    # ---- Daily macro line ----
    protein = cut.get("protein_per_day_g", 150)
    L.append(f"**Will daily (cut ~{protein}g protein):** shake+flax/chia · "
             f"{closer.get('preferred', 'larger portion of an existing high-protein item')} as the closer · "
             f"fill with on-hand items first, then in-season fruit (bananas only in shakes) → TODO cal/protein line")
    L.append("")
    L.append("Sat M2 = hot dogs. M1 = shakes daily. Elena M1 = protein bars.")
    L.append("")

    out_path.write_text("\n".join(L), encoding="utf-8")
    print(f"Wrote {out_path}")
    print("Scaffold only — fill the week-at-a-glance day mapping + portion notes, then commit/push for phone access.")


if __name__ == "__main__":
    main()
